# Generated by Django 3.1.4 on 2021-05-29 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrera',
        ),
    ]
