# Generated by Django 3.1.4 on 2021-05-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_habitacion', models.CharField(max_length=50)),
                ('tipo_habitacion', models.CharField(max_length=100)),
                ('precio_por_noche', models.IntegerField()),
                ('cantidad_camas', models.CharField(max_length=50)),
                ('cantidad_baños', models.CharField(max_length=50)),
                ('tipo_cama', models.CharField(max_length=100)),
                ('tipo_baño', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='habitaciones')),
            ],
        ),
    ]
