# Generated by Django 3.1.4 on 2021-05-29 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=250)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('rubro', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=250)),
                ('direccion', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=250)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('cantidad_personas', models.IntegerField()),
                ('fecha_llegada', models.DateField()),
                ('fecha_ida', models.DateField()),
                ('empresa', models.CharField(max_length=50)),
                ('rut_empresa', models.CharField(max_length=50)),
                ('rubro', models.CharField(max_length=100)),
                ('telefono_empresa', models.CharField(max_length=50)),
                ('correo_empresa', models.CharField(max_length=50)),
                ('direccion_empresa', models.TextField()),
                ('Habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=250)),
                ('direccion', models.TextField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.marca')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=250)),
                ('telefono', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.empresa')),
            ],
        ),
    ]
