# Generated by Django 3.1.4 on 2021-05-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0008_comedor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedor',
            name='imagen',
            field=models.ImageField(null=True, upload_to='comedor'),
        ),
    ]
