# Generated by Django 3.2.4 on 2021-06-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0011_auto_20210605_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='asunto',
            field=models.IntegerField(choices=[[0, 'Problema'], [1, 'Reservar'], [2, 'Solicitud'], [2, 'Registro Usuario'], [3, 'Cancelar']]),
        ),
    ]
