# Generated by Django 3.2.4 on 2021-06-06 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0013_alter_cliente_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.empresa'),
        ),
    ]
