# Generated by Django 3.2.4 on 2021-06-06 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0014_alter_proveedor_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedor',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.servicio'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.marca'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.producto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.proveedor'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='Habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.habitacion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.producto'),
        ),
    ]
