# Generated by Django 3.2.4 on 2021-06-06 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0016_auto_20210606_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.empresa'),
        ),
    ]
