# Generated by Django 3.2.4 on 2021-06-06 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0018_alter_proveedor_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Web.proveedor'),
        ),
    ]
