# Generated by Django 3.2.4 on 2021-06-06 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0019_alter_empleado_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='proveedor',
        ),
    ]
