# Generated by Django 3.2.4 on 2021-06-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0021_alter_proveedor_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huesped',
            name='Habitacion',
        ),
        migrations.DeleteModel(
            name='Habitacion',
        ),
        migrations.DeleteModel(
            name='Huesped',
        ),
    ]
