# Generated by Django 3.2.4 on 2021-07-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0024_auto_20210629_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.ImageField(upload_to='')),
                ('nombre_habitacion', models.CharField(max_length=100)),
                ('tipo_habitacion', models.CharField(choices=[('PRIV', 'PRIVADA'), ('COMP', 'COMPARTIDA'), ('PRIV', 'PRIVADA'), ('COMP', 'COMPARTIDA')], max_length=100)),
                ('camas', models.IntegerField()),
                ('baños', models.IntegerField()),
                ('capacidad_personas', models.IntegerField()),
                ('estado_habitacion', models.CharField(choices=[[0, 'Disponible'], [1, 'No Disponible (Ocupada)'], [2, 'No Disponible (En Mantencion)']], max_length=3)),
            ],
        ),
    ]
