# Generated by Django 3.2.4 on 2021-07-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0025_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='number',
            field=models.IntegerField(),
        ),
    ]
