# Generated by Django 3.2.4 on 2021-07-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0026_alter_habitacion_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='number',
            new_name='numero',
        ),
    ]
