# Generated by Django 3.2.4 on 2021-07-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0027_rename_number_habitacion_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado_habitacion',
            field=models.CharField(choices=[[1, 'Disponible'], [2, 'No Disponible (En Mantencion)'], [3, 'No Disponible (Reservada a empresa)']], max_length=3),
        ),
    ]
