# Generated by Django 3.2.4 on 2021-07-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0031_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='user',
            new_name='usuario',
        ),
    ]
