# Generated by Django 3.2.4 on 2021-07-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0032_rename_user_reserva_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='tipo_habitacion',
            new_name='categoria',
        ),
    ]
