# Generated by Django 3.2.4 on 2021-07-05 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0033_rename_tipo_habitacion_habitacion_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=250)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('cantidad_personas', models.IntegerField()),
                ('fecha_llegada', models.DateField()),
                ('fecha_ida', models.DateField()),
                ('empresa', models.CharField(max_length=50)),
                ('rut_empresa', models.CharField(max_length=50)),
                ('rubro', models.CharField(max_length=100)),
                ('telefono_empresa', models.CharField(max_length=50)),
                ('correo_empresa', models.CharField(max_length=50)),
                ('direccion_empresa', models.TextField()),
                ('Habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.habitacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
