# Generated by Django 3.2.4 on 2021-07-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0034_huesped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='categoria',
            field=models.CharField(choices=[('PRIVADA', 'PRIVADA'), ('COMPARTIDA', 'COMPARTIDA')], max_length=100),
        ),
    ]
