# Generated by Django 3.2.4 on 2021-07-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0035_alter_habitacion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='habitaciones'),
        ),
    ]
