# Generated by Django 3.2.4 on 2021-07-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0036_habitacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='categoria',
            field=models.CharField(choices=[('PRIV', 'PRIVADA'), ('COMP', 'COMPARTIDA')], max_length=100),
        ),
    ]
