# Generated by Django 3.2.4 on 2021-07-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0037_alter_habitacion_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='categoria',
            field=models.CharField(choices=[('priv', 'PRIVADA'), ('comp', 'COMPARTIDA')], max_length=100),
        ),
    ]
