# Generated by Django 3.2.4 on 2021-07-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0038_alter_habitacion_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='categoria',
            field=models.CharField(choices=[('priv', 'DORMITORIO ORO'), ('comp', 'DORMITORIO BRONCE')], max_length=100),
        ),
    ]
