# Generated by Django 3.2.4 on 2021-07-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0039_alter_habitacion_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huesped',
            name='Habitacion',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='habitacion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Habitacion',
        ),
        migrations.DeleteModel(
            name='Huesped',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
