# Generated by Django 3.2.4 on 2021-07-08 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0040_auto_20210708_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre_habitacion', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('privada-1', 'DORMITORIO ORO 1'), ('privada-2', 'DORMITORIO ORO 2'), ('compartida-1', 'DORMITORIO PLATA 1'), ('compartida-2', 'DORMITORIO PLATA 2')], max_length=100)),
                ('camas', models.IntegerField()),
                ('baños', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('capacidad_personas', models.IntegerField()),
                ('estado_habitacion', models.IntegerField(choices=[[0, 'Disponible '], [1, 'No Disponible'], [3, 'En Mantenimiento'], [4, 'Fuera de servicio']])),
                ('imagen', models.ImageField(null=True, upload_to='habitaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('precio', models.IntegerField()),
                ('cantidad_personas', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('R', 'Aprobada'), ('C', 'Cancelada')], default='R', max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.empresa')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.habitacion')),
            ],
        ),
    ]
