# Generated by Django 3.2.4 on 2021-07-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0043_habitacion_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='check_out',
            field=models.DateTimeField(),
        ),
    ]
