# Generated by Django 3.2.4 on 2021-07-08 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0044_auto_20210708_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cantidad_personas',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='precio',
        ),
    ]
