# Generated by Django 3.2.4 on 2021-07-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0046_remove_reserva_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('A', 'Aprobada'), ('C', 'Cancelada')], default='A', max_length=2),
        ),
    ]
