# Generated by Django 3.2.4 on 2021-07-11 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0049_ordenpedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdenPedido',
            new_name='Pedido',
        ),
    ]
