# Generated by Django 3.2.4 on 2021-07-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0050_rename_ordenpedido_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
