# Generated by Django 3.2.4 on 2021-07-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0052_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
