# Generated by Django 3.2.4 on 2021-07-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0055_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Proveedor', 'Proveedor'), ('Empleado', 'Empleado'), ('Huesped', 'Huesped'), ('Administrador', 'Administrador')], default='Cliente', max_length=50),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
