# Generated by Django 3.2.4 on 2021-07-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0057_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='familia_producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tipo_producto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
