# Generated by Django 3.2.4 on 2021-07-12 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0058_auto_20210712_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, null=True)),
                ('apellido', models.CharField(max_length=120, null=True)),
                ('rut', models.CharField(max_length=100, null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('rubro', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('direccion', models.TextField()),
                ('proveedor_id', models.CharField(max_length=3, null=True)),
                ('perfil', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Web.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=500, null=True)),
                ('nombre', models.CharField(max_length=120, null=True)),
                ('apellido', models.CharField(max_length=120, null=True)),
                ('rut', models.CharField(max_length=100, null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('numero', models.CharField(max_length=100, null=True)),
                ('client_id', models.CharField(max_length=200, null=True)),
                ('perfil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.perfil')),
            ],
        ),
    ]
