# Generated by Django 3.2.4 on 2021-07-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0059_cliente_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
