# Generated by Django 3.2.4 on 2021-07-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0060_auto_20210712_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
