# Generated by Django 3.2.4 on 2021-07-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0061_delete_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Proveedor', 'Proveedor'), ('Empleado', 'Empleado'), ('Huesped', 'Huesped')], default='Cliente', max_length=50),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, null=True)),
                ('apellido', models.CharField(max_length=120, null=True)),
                ('rut', models.CharField(max_length=100, null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('rubro', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('direccion', models.TextField()),
                ('proveedor_id', models.CharField(max_length=3, null=True)),
                ('perfil', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Web.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=500, null=True)),
                ('rut', models.CharField(max_length=100, null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('huesped_id', models.CharField(max_length=200, null=True)),
                ('perfil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=250)),
                ('direccion', models.TextField()),
                ('empleado_id', models.CharField(max_length=200, null=True)),
                ('perfil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=500, null=True)),
                ('nombre', models.CharField(max_length=120, null=True)),
                ('apellido', models.CharField(max_length=120, null=True)),
                ('rut', models.CharField(max_length=100, null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('client_id', models.CharField(max_length=200, null=True)),
                ('perfil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.perfil')),
            ],
        ),
    ]
