# Generated by Django 3.2.4 on 2021-07-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0065_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='client_id',
            new_name='cliente_id',
        ),
    ]
