# Generated by Django 3.2.4 on 2021-07-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0066_rename_client_id_cliente_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado_habitacion',
            field=models.IntegerField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible'), ('En Mantenimiento', 'En Mantenimiento'), ('Fuera de servicio', 'Fuera de servicio')]),
        ),
    ]
