# Generated by Django 3.2.4 on 2021-07-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0068_alter_habitacion_estado_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado_habitacion',
            field=models.IntegerField(choices=[[0, 'Disponible '], [1, 'No Disponible '], [2, 'En Mantenimiento'], [3, 'Fuera de servicio']]),
        ),
    ]
