# Generated by Django 3.2.4 on 2021-07-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0072_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='correo',
            new_name='correo_empleado',
        ),
    ]
