# Generated by Django 3.2.4 on 2021-07-15 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0074_ordencompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.servicio'),
        ),
    ]
