# Generated by Django 3.2.4 on 2021-07-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0076_remove_ordencompra_comentarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
    ]
