# Generated by Django 3.2.4 on 2021-07-15 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0079_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
