# Generated by Django 3.2.4 on 2021-07-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0080_auto_20210715_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('nuevo', models.BooleanField()),
                ('fecha_vencimiento', models.DateField()),
                ('stock_disponible', models.CharField(max_length=200)),
                ('stock_critico', models.CharField(max_length=200)),
                ('familia_producto', models.ForeignKey(blank=True, db_column='nro_familia_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.familiaproducto')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.marca')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.proveedor')),
                ('tipo_producto', models.ForeignKey(blank=True, db_column='nro_tipo_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_critico', models.IntegerField(blank=True, default=10, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Web.producto')),
            ],
        ),
    ]
