# Generated by Django 3.2.4 on 2021-07-16 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0081_producto_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdenCompra',
            new_name='Compra',
        ),
    ]
