# Generated by Django 3.2.4 on 2021-07-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0082_rename_ordencompra_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado_habitacion',
            field=models.IntegerField(choices=[[0, 'Disponible'], [1, 'No Disponible'], [2, 'En Mantencion'], [3, 'Fuera de servicio']]),
        ),
    ]
