# Generated by Django 3.2.4 on 2021-07-18 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0084_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual',
            name='author',
        ),
    ]
