# Generated by Django 3.2.4 on 2021-07-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0085_remove_manual_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arhivo', models.FileField(upload_to='manuales/pdfs/')),
            ],
        ),
    ]
