# Generated by Django 3.2.4 on 2021-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0090_delete_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='documentos/pdfs/')),
            ],
        ),
    ]
