# Generated by Django 3.2.4 on 2021-07-18 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0091_archivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manual',
        ),
    ]
