# Generated by Django 3.2.4 on 2021-07-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0093_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('completa', models.BooleanField(default=False, null=True)),
                ('transaccion_id', models.CharField(max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.CharField(max_length=200)),
                ('habitacion', models.CharField(default='Hostal Don Pepe', max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=200)),
                ('detalle', models.CharField(max_length=200)),
                ('giro', models.CharField(max_length=200)),
                ('orden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Web.orden')),
            ],
        ),
    ]
