# Generated by Django 3.2.4 on 2021-07-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0095_auto_20210718_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
