# Generated by Django 4.1.1 on 2022-10-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0104_alter_contacto_asunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='asunto',
            field=models.IntegerField(choices=[[0, 'Problema'], [1, 'Reservar'], [2, 'Solicitud'], [3, 'Registro Usuario'], [4, 'Solicitud cambio de contraseña'], [5, 'Cancelar']]),
        ),
    ]
